package com.driezy.medlog.ui.icons

// Generated by scripts/update_material_symbols.mjs.
// Source: Google Fonts Material Symbols Rounded VectorDrawable-compatible paths.
// Baseline icons use 24dp. Selected navigation icons use fill=1 variants.
// Display icons use optical-size-specific 40dp or 48dp variants.

import androidx.annotation.DrawableRes
import androidx.compose.material3.Icon as MaterialIcon
import androidx.compose.material3.LocalContentColor
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.painterResource
import com.driezy.medlog.R

object MedLogIcons {
    @DrawableRes val AccessAlarm: Int = R.drawable.ic_symbol_access_alarm
    @DrawableRes val AccessTime: Int = R.drawable.ic_symbol_access_time
    @DrawableRes val Add: Int = R.drawable.ic_symbol_add
    @DrawableRes val AddToHomeScreen: Int = R.drawable.ic_symbol_add_to_home_screen
    @DrawableRes val Adjust: Int = R.drawable.ic_symbol_adjust
    @DrawableRes val AirlineStops: Int = R.drawable.ic_symbol_airline_stops
    @DrawableRes val AlarmAdd: Int = R.drawable.ic_symbol_alarm_add
    @DrawableRes val Archive: Int = R.drawable.ic_symbol_archive
    @DrawableRes val ArrowBack: Int = R.drawable.ic_symbol_arrow_back
    @DrawableRes val ArrowForward: Int = R.drawable.ic_symbol_arrow_forward
    @DrawableRes val AutoAwesome: Int = R.drawable.ic_symbol_auto_awesome
    @DrawableRes val Bedtime: Int = R.drawable.ic_symbol_bedtime
    @DrawableRes val Bloodtype: Int = R.drawable.ic_symbol_bloodtype
    @DrawableRes val BreakfastDining: Int = R.drawable.ic_symbol_breakfast_dining
    @DrawableRes val Brightness5: Int = R.drawable.ic_symbol_brightness_5
    @DrawableRes val CalendarMonth: Int = R.drawable.ic_symbol_calendar_month
    @DrawableRes val CameraAlt: Int = R.drawable.ic_symbol_photo_camera
    @DrawableRes val Cancel: Int = R.drawable.ic_symbol_cancel
    @DrawableRes val Category: Int = R.drawable.ic_symbol_category
    @DrawableRes val CenterFocusStrong: Int = R.drawable.ic_symbol_center_focus_strong
    @DrawableRes val Check: Int = R.drawable.ic_symbol_check
    @DrawableRes val CheckCircle: Int = R.drawable.ic_symbol_check_circle
    @DrawableRes val ChevronRight: Int = R.drawable.ic_symbol_chevron_right
    @DrawableRes val Close: Int = R.drawable.ic_symbol_close
    @DrawableRes val CloudUpload: Int = R.drawable.ic_symbol_cloud_upload
    @DrawableRes val Coffee: Int = R.drawable.ic_symbol_coffee
    @DrawableRes val ColorLens: Int = R.drawable.ic_symbol_color_lens
    @DrawableRes val DarkMode: Int = R.drawable.ic_symbol_dark_mode
    @DrawableRes val DateRange: Int = R.drawable.ic_symbol_date_range
    @DrawableRes val Delete: Int = R.drawable.ic_symbol_delete
    @DrawableRes val DinnerDining: Int = R.drawable.ic_symbol_dinner_dining
    @DrawableRes val DocumentScanner: Int = R.drawable.ic_symbol_document_scanner
    @DrawableRes val DoneAll: Int = R.drawable.ic_symbol_done_all
    @DrawableRes val Edit: Int = R.drawable.ic_symbol_edit
    @DrawableRes val EditNote: Int = R.drawable.ic_symbol_edit_note
    @DrawableRes val EventRepeat: Int = R.drawable.ic_symbol_event_repeat
    @DrawableRes val ExpandLess: Int = R.drawable.ic_symbol_expand_less
    @DrawableRes val ExpandMore: Int = R.drawable.ic_symbol_expand_more
    @DrawableRes val Favorite: Int = R.drawable.ic_symbol_favorite
    @DrawableRes val FitnessCenter: Int = R.drawable.ic_symbol_fitness_center
    @DrawableRes val FlashOff: Int = R.drawable.ic_symbol_flash_off
    @DrawableRes val FlashOn: Int = R.drawable.ic_symbol_flash_on
    @DrawableRes val FlightTakeoff: Int = R.drawable.ic_symbol_flight_takeoff
    @DrawableRes val Healing: Int = R.drawable.ic_symbol_healing
    @DrawableRes val History: Int = R.drawable.ic_symbol_history
    @DrawableRes val Home: Int = R.drawable.ic_symbol_home
    @DrawableRes val HourglassBottom: Int = R.drawable.ic_symbol_hourglass_bottom
    @DrawableRes val Info: Int = R.drawable.ic_symbol_info
    @DrawableRes val Inventory: Int = R.drawable.ic_symbol_inventory
    @DrawableRes val Inventory2: Int = R.drawable.ic_symbol_inventory_2
    @DrawableRes val IosShare: Int = R.drawable.ic_symbol_ios_share
    @DrawableRes val LightMode: Int = R.drawable.ic_symbol_light_mode
    @DrawableRes val LocalDrink: Int = R.drawable.ic_symbol_local_drink
    @DrawableRes val LocalFlorist: Int = R.drawable.ic_symbol_local_florist
    @DrawableRes val LunchDining: Int = R.drawable.ic_symbol_lunch_dining
    @DrawableRes val MedicalServices: Int = R.drawable.ic_symbol_medical_services
    @DrawableRes val Medication: Int = R.drawable.ic_symbol_medication
    @DrawableRes val Memory: Int = R.drawable.ic_symbol_memory
    @DrawableRes val Monitor: Int = R.drawable.ic_symbol_monitor
    @DrawableRes val MonitorHeart: Int = R.drawable.ic_symbol_monitor_heart
    @DrawableRes val MonitorWeight: Int = R.drawable.ic_symbol_monitor_weight
    @DrawableRes val MoreHoriz: Int = R.drawable.ic_symbol_more_horiz
    @DrawableRes val MoreVert: Int = R.drawable.ic_symbol_more_vert
    @DrawableRes val NightsStay: Int = R.drawable.ic_symbol_nights_stay
    @DrawableRes val Notes: Int = R.drawable.ic_symbol_notes
    @DrawableRes val NotificationAdd: Int = R.drawable.ic_symbol_notification_add
    @DrawableRes val Notifications: Int = R.drawable.ic_symbol_notifications
    @DrawableRes val NotificationsActive: Int = R.drawable.ic_symbol_notifications_active
    @DrawableRes val NotificationsOff: Int = R.drawable.ic_symbol_notifications_off
    @DrawableRes val OpenInNew: Int = R.drawable.ic_symbol_open_in_new
    @DrawableRes val Palette: Int = R.drawable.ic_symbol_palette
    @DrawableRes val PanTool: Int = R.drawable.ic_symbol_pan_tool
    @DrawableRes val PriorityHigh: Int = R.drawable.ic_symbol_priority_high
    @DrawableRes val QrCode2: Int = R.drawable.ic_symbol_qr_code_2
    @DrawableRes val QrCodeScanner: Int = R.drawable.ic_symbol_qr_code_scanner
    @DrawableRes val Refresh: Int = R.drawable.ic_symbol_refresh
    @DrawableRes val Remove: Int = R.drawable.ic_symbol_remove
    @DrawableRes val Replay: Int = R.drawable.ic_symbol_replay
    @DrawableRes val Schedule: Int = R.drawable.ic_symbol_schedule
    @DrawableRes val Science: Int = R.drawable.ic_symbol_science
    @DrawableRes val Search: Int = R.drawable.ic_symbol_search
    @DrawableRes val SearchOff: Int = R.drawable.ic_symbol_search_off
    @DrawableRes val Settings: Int = R.drawable.ic_symbol_settings
    @DrawableRes val SkipNext: Int = R.drawable.ic_symbol_skip_next
    @DrawableRes val Speed: Int = R.drawable.ic_symbol_speed
    @DrawableRes val Storage: Int = R.drawable.ic_symbol_storage
    @DrawableRes val Thermostat: Int = R.drawable.ic_symbol_thermostat
    @DrawableRes val Timer: Int = R.drawable.ic_symbol_timer
    @DrawableRes val Today: Int = R.drawable.ic_symbol_today
    @DrawableRes val TouchApp: Int = R.drawable.ic_symbol_touch_app
    @DrawableRes val TrendingUp: Int = R.drawable.ic_symbol_trending_up
    @DrawableRes val Tune: Int = R.drawable.ic_symbol_tune
    @DrawableRes val Undo: Int = R.drawable.ic_symbol_undo
    @DrawableRes val UnfoldLess: Int = R.drawable.ic_symbol_unfold_less
    @DrawableRes val Upload: Int = R.drawable.ic_symbol_upload
    @DrawableRes val VerifiedUser: Int = R.drawable.ic_symbol_verified_user
    @DrawableRes val ViewAgenda: Int = R.drawable.ic_symbol_view_agenda
    @DrawableRes val Warning: Int = R.drawable.ic_symbol_warning
    @DrawableRes val WaterDrop: Int = R.drawable.ic_symbol_water_drop
    @DrawableRes val WbSunny: Int = R.drawable.ic_symbol_wb_sunny
    @DrawableRes val Widgets: Int = R.drawable.ic_symbol_widgets

    @DrawableRes val HomeSelected: Int = R.drawable.ic_symbol_home_fill1
    @DrawableRes val HistorySelected: Int = R.drawable.ic_symbol_history_fill1
    @DrawableRes val MedicalServicesSelected: Int = R.drawable.ic_symbol_medical_services_fill1
    @DrawableRes val EditNoteSelected: Int = R.drawable.ic_symbol_edit_note_fill1
    @DrawableRes val MonitorHeartSelected: Int = R.drawable.ic_symbol_monitor_heart_fill1
    @DrawableRes val SettingsSelected: Int = R.drawable.ic_symbol_settings_fill1

    @DrawableRes val MedicationDisplay40: Int = R.drawable.ic_symbol_medication_opsz40
    @DrawableRes val RefreshDisplay48: Int = R.drawable.ic_symbol_refresh_opsz48
    @DrawableRes val MonitorHeartDisplay48: Int = R.drawable.ic_symbol_monitor_heart_opsz48
    @DrawableRes val SearchOffDisplay48: Int = R.drawable.ic_symbol_search_off_opsz48
    @DrawableRes val CheckCircleDisplay48: Int = R.drawable.ic_symbol_check_circle_opsz48
}

@Composable
fun MedLogIcon(
    @DrawableRes icon: Int,
    contentDescription: String?,
    modifier: Modifier = Modifier,
    tint: Color = LocalContentColor.current,
) {
    MaterialIcon(
        painter = painterResource(icon),
        contentDescription = contentDescription,
        modifier = modifier,
        tint = tint,
    )
}
