package com.driezy.medlog.ui.theme

import androidx.annotation.StringRes
import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color
import com.driezy.medlog.R

enum class ThemePalette(
    val displayName: String,
    @param:StringRes val descriptionRes: Int,
    val imagery: String,
    val allowsDynamicColor: Boolean = false,
    private val lightSchemeProvider: () -> ColorScheme,
    private val darkSchemeProvider: () -> ColorScheme,
) {
    ANSHIN(
        displayName = "Anshin",
        descriptionRes = R.string.settings_palette_desc_anshin,
        imagery = "medical blue, clean green, clear daylight",
        allowsDynamicColor = true,
        lightSchemeProvider = { MedLogLightColorScheme },
        darkSchemeProvider = { MedLogDarkColorScheme },
    ),
    MEADOW(
        displayName = "Meadow · 青青草",
        descriptionRes = R.string.settings_palette_desc_meadow,
        imagery = "meadow grass, morning dew, soft low-chroma green",
        lightSchemeProvider = { MeadowLightColors },
        darkSchemeProvider = { MeadowDarkColors },
    ),
    WAKAKUSA(
        displayName = "Wakakusa · 若草",
        descriptionRes = R.string.settings_palette_desc_wakakusa,
        imagery = "new spring grass, pale yellow-green, quiet paper tones",
        lightSchemeProvider = { WakakusaLightColors },
        darkSchemeProvider = { WakakusaDarkColors },
    ),
    CELADON(
        displayName = "Celadon · 青瓷",
        descriptionRes = R.string.settings_palette_desc_celadon,
        imagery = "celadon glaze, mist, still blue-green water",
        lightSchemeProvider = { CeladonLightColors },
        darkSchemeProvider = { CeladonDarkColors },
    ),
    AUBE(
        displayName = "Aube · 曙光",
        descriptionRes = R.string.settings_palette_desc_aube,
        imagery = "first dawn light, warm amber, muted earth",
        lightSchemeProvider = { AubeLightColors },
        darkSchemeProvider = { AubeDarkColors },
    ),
    ;

    val lightColorScheme: ColorScheme
        get() = lightSchemeProvider()

    val darkColorScheme: ColorScheme
        get() = darkSchemeProvider()

    fun colorScheme(darkTheme: Boolean): ColorScheme = if (darkTheme) darkColorScheme else lightColorScheme

    companion object {
        fun fromStoredName(name: String?): ThemePalette = entries.firstOrNull { it.name == name } ?: ANSHIN
    }
}

private fun ColorScheme.withPalette(
    primary: Color,
    onPrimary: Color,
    primaryContainer: Color,
    onPrimaryContainer: Color,
    secondary: Color,
    onSecondary: Color,
    secondaryContainer: Color,
    onSecondaryContainer: Color,
    tertiary: Color,
    onTertiary: Color,
    tertiaryContainer: Color,
    onTertiaryContainer: Color,
    background: Color,
    onBackground: Color,
    surface: Color,
    onSurface: Color,
    surfaceVariant: Color,
    onSurfaceVariant: Color,
    outline: Color,
    outlineVariant: Color,
    inverseSurface: Color,
    inverseOnSurface: Color,
    surfaceContainerLow: Color,
    surfaceContainer: Color,
    surfaceContainerHigh: Color,
    surfaceContainerHighest: Color,
): ColorScheme = copy(
    primary = primary,
    onPrimary = onPrimary,
    primaryContainer = primaryContainer,
    onPrimaryContainer = onPrimaryContainer,
    secondary = secondary,
    onSecondary = onSecondary,
    secondaryContainer = secondaryContainer,
    onSecondaryContainer = onSecondaryContainer,
    tertiary = tertiary,
    onTertiary = onTertiary,
    tertiaryContainer = tertiaryContainer,
    onTertiaryContainer = onTertiaryContainer,
    background = background,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    surfaceVariant = surfaceVariant,
    onSurfaceVariant = onSurfaceVariant,
    outline = outline,
    outlineVariant = outlineVariant,
    inverseSurface = inverseSurface,
    inverseOnSurface = inverseOnSurface,
    inversePrimary = primaryContainer,
    surfaceTint = primary,
    surfaceContainerLowest = surface,
    surfaceContainerLow = surfaceContainerLow,
    surfaceContainer = surfaceContainer,
    surfaceContainerHigh = surfaceContainerHigh,
    surfaceContainerHighest = surfaceContainerHighest,
    primaryFixed = primaryContainer,
    primaryFixedDim = primaryContainer,
    onPrimaryFixed = onPrimaryContainer,
    onPrimaryFixedVariant = primary,
    secondaryFixed = secondaryContainer,
    secondaryFixedDim = secondaryContainer,
    onSecondaryFixed = onSecondaryContainer,
    onSecondaryFixedVariant = secondary,
    tertiaryFixed = tertiaryContainer,
    tertiaryFixedDim = tertiaryContainer,
    onTertiaryFixed = onTertiaryContainer,
    onTertiaryFixedVariant = tertiary,
)

private val MeadowLightColors = MedLogLightColorScheme.withPalette(
    primary = Color(0xFF4C6F2F),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFCDEEA6),
    onPrimaryContainer = Color(0xFF102000),
    secondary = Color(0xFF53643E),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD7E9BC),
    onSecondaryContainer = Color(0xFF111F04),
    tertiary = Color(0xFF386664),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFBCECEA),
    onTertiaryContainer = Color(0xFF00201F),
    background = Color(0xFFF8FAF0),
    onBackground = Color(0xFF1B1D17),
    surface = Color(0xFFF8FAF0),
    onSurface = Color(0xFF1B1D17),
    surfaceVariant = Color(0xFFE1E5D6),
    onSurfaceVariant = Color(0xFF45483E),
    outline = Color(0xFF75786D),
    outlineVariant = Color(0xFFC5C9BA),
    inverseSurface = Color(0xFF30312C),
    inverseOnSurface = Color(0xFFF1F2E8),
    surfaceContainerLow = Color(0xFFF2F4EA),
    surfaceContainer = Color(0xFFECEEE4),
    surfaceContainerHigh = Color(0xFFE6E8DE),
    surfaceContainerHighest = Color(0xFFE0E3D9),
)

private val MeadowDarkColors = MedLogDarkColorScheme.withPalette(
    primary = Color(0xFFB2D28B),
    onPrimary = Color(0xFF203600),
    primaryContainer = Color(0xFF354E17),
    onPrimaryContainer = Color(0xFFCDEEA6),
    secondary = Color(0xFFBBCDA2),
    onSecondary = Color(0xFF263516),
    secondaryContainer = Color(0xFF3C4C2B),
    onSecondaryContainer = Color(0xFFD7E9BC),
    tertiary = Color(0xFFA0CFCD),
    onTertiary = Color(0xFF003735),
    tertiaryContainer = Color(0xFF1E4E4C),
    onTertiaryContainer = Color(0xFFBCECEA),
    background = Color(0xFF13150F),
    onBackground = Color(0xFFE3E4DA),
    surface = Color(0xFF13150F),
    onSurface = Color(0xFFE3E4DA),
    surfaceVariant = Color(0xFF45483E),
    onSurfaceVariant = Color(0xFFC5C9BA),
    outline = Color(0xFF8F9286),
    outlineVariant = Color(0xFF45483E),
    inverseSurface = Color(0xFFE3E4DA),
    inverseOnSurface = Color(0xFF30312C),
    surfaceContainerLow = Color(0xFF1B1D17),
    surfaceContainer = Color(0xFF1F211B),
    surfaceContainerHigh = Color(0xFF292B25),
    surfaceContainerHighest = Color(0xFF34362F),
)

private val WakakusaLightColors = MedLogLightColorScheme.withPalette(
    primary = Color(0xFF5E6723),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE3EC98),
    onPrimaryContainer = Color(0xFF1B1F00),
    secondary = Color(0xFF5D6145),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE2E6C3),
    onSecondaryContainer = Color(0xFF1A1D08),
    tertiary = Color(0xFF3B6654),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFBDECD5),
    onTertiaryContainer = Color(0xFF002117),
    background = Color(0xFFFCF9EA),
    onBackground = Color(0xFF1D1C14),
    surface = Color(0xFFFCF9EA),
    onSurface = Color(0xFF1D1C14),
    surfaceVariant = Color(0xFFE6E3D0),
    onSurfaceVariant = Color(0xFF49473A),
    outline = Color(0xFF7A7768),
    outlineVariant = Color(0xFFCAC7B5),
    inverseSurface = Color(0xFF323127),
    inverseOnSurface = Color(0xFFF4F1E2),
    surfaceContainerLow = Color(0xFFF6F3E4),
    surfaceContainer = Color(0xFFF0EEDF),
    surfaceContainerHigh = Color(0xFFEAE8D9),
    surfaceContainerHighest = Color(0xFFE4E2D3),
)

private val WakakusaDarkColors = MedLogDarkColorScheme.withPalette(
    primary = Color(0xFFC6D07F),
    onPrimary = Color(0xFF303600),
    primaryContainer = Color(0xFF464E0D),
    onPrimaryContainer = Color(0xFFE3EC98),
    secondary = Color(0xFFC6CAAA),
    onSecondary = Color(0xFF2F331B),
    secondaryContainer = Color(0xFF454930),
    onSecondaryContainer = Color(0xFFE2E6C3),
    tertiary = Color(0xFFA2D0BA),
    onTertiary = Color(0xFF073728),
    tertiaryContainer = Color(0xFF234E3D),
    onTertiaryContainer = Color(0xFFBDECD5),
    background = Color(0xFF15140C),
    onBackground = Color(0xFFE7E2D4),
    surface = Color(0xFF15140C),
    onSurface = Color(0xFFE7E2D4),
    surfaceVariant = Color(0xFF49473A),
    onSurfaceVariant = Color(0xFFCAC7B5),
    outline = Color(0xFF949181),
    outlineVariant = Color(0xFF49473A),
    inverseSurface = Color(0xFFE7E2D4),
    inverseOnSurface = Color(0xFF323127),
    surfaceContainerLow = Color(0xFF1D1C14),
    surfaceContainer = Color(0xFF222018),
    surfaceContainerHigh = Color(0xFF2C2B22),
    surfaceContainerHighest = Color(0xFF37362C),
)

private val CeladonLightColors = MedLogLightColorScheme.withPalette(
    primary = Color(0xFF2D6B5F),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFB2F0E2),
    onPrimaryContainer = Color(0xFF00201B),
    secondary = Color(0xFF4A635D),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCDE8E0),
    onSecondaryContainer = Color(0xFF06201B),
    tertiary = Color(0xFF456179),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFCCE5FF),
    onTertiaryContainer = Color(0xFF001E31),
    background = Color(0xFFF3FBF8),
    onBackground = Color(0xFF171D1B),
    surface = Color(0xFFF3FBF8),
    onSurface = Color(0xFF171D1B),
    surfaceVariant = Color(0xFFDBE5E1),
    onSurfaceVariant = Color(0xFF3F4946),
    outline = Color(0xFF6F7976),
    outlineVariant = Color(0xFFBFC9C5),
    inverseSurface = Color(0xFF2C322F),
    inverseOnSurface = Color(0xFFEBF3EF),
    surfaceContainerLow = Color(0xFFEDF5F2),
    surfaceContainer = Color(0xFFE7EFEC),
    surfaceContainerHigh = Color(0xFFE1E9E6),
    surfaceContainerHighest = Color(0xFFDBE4E0),
)

private val CeladonDarkColors = MedLogDarkColorScheme.withPalette(
    primary = Color(0xFF96D4C6),
    onPrimary = Color(0xFF003730),
    primaryContainer = Color(0xFF0B5047),
    onPrimaryContainer = Color(0xFFB2F0E2),
    secondary = Color(0xFFB1CCC4),
    onSecondary = Color(0xFF1D352F),
    secondaryContainer = Color(0xFF334B45),
    onSecondaryContainer = Color(0xFFCDE8E0),
    tertiary = Color(0xFFACC9E6),
    onTertiary = Color(0xFF143349),
    tertiaryContainer = Color(0xFF2D4960),
    onTertiaryContainer = Color(0xFFCCE5FF),
    background = Color(0xFF0F1513),
    onBackground = Color(0xFFDDE5E1),
    surface = Color(0xFF0F1513),
    onSurface = Color(0xFFDDE5E1),
    surfaceVariant = Color(0xFF3F4946),
    onSurfaceVariant = Color(0xFFBFC9C5),
    outline = Color(0xFF89938F),
    outlineVariant = Color(0xFF3F4946),
    inverseSurface = Color(0xFFDDE5E1),
    inverseOnSurface = Color(0xFF2C322F),
    surfaceContainerLow = Color(0xFF171D1B),
    surfaceContainer = Color(0xFF1B211F),
    surfaceContainerHigh = Color(0xFF252B29),
    surfaceContainerHighest = Color(0xFF303633),
)

private val AubeLightColors = MedLogLightColorScheme.withPalette(
    primary = Color(0xFF8A4B00),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDCC0),
    onPrimaryContainer = Color(0xFF2C1600),
    secondary = Color(0xFF755944),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDCC8),
    onSecondaryContainer = Color(0xFF2B1708),
    tertiary = Color(0xFF5F6136),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFE5E7AE),
    onTertiaryContainer = Color(0xFF1C1D00),
    background = Color(0xFFFFF8F3),
    onBackground = Color(0xFF211A15),
    surface = Color(0xFFFFF8F3),
    onSurface = Color(0xFF211A15),
    surfaceVariant = Color(0xFFF2DFD2),
    onSurfaceVariant = Color(0xFF50443B),
    outline = Color(0xFF82746A),
    outlineVariant = Color(0xFFD5C3B6),
    inverseSurface = Color(0xFF362F29),
    inverseOnSurface = Color(0xFFFBEDE4),
    surfaceContainerLow = Color(0xFFFFF1E8),
    surfaceContainer = Color(0xFFF9ECE2),
    surfaceContainerHigh = Color(0xFFF3E6DC),
    surfaceContainerHighest = Color(0xFFEDE0D7),
)

private val AubeDarkColors = MedLogDarkColorScheme.withPalette(
    primary = Color(0xFFFFB86F),
    onPrimary = Color(0xFF492900),
    primaryContainer = Color(0xFF693C00),
    onPrimaryContainer = Color(0xFFFFDCC0),
    secondary = Color(0xFFE5BFA6),
    onSecondary = Color(0xFF422B1A),
    secondaryContainer = Color(0xFF5B412F),
    onSecondaryContainer = Color(0xFFFFDCC8),
    tertiary = Color(0xFFC9CB94),
    onTertiary = Color(0xFF30330C),
    tertiaryContainer = Color(0xFF47491F),
    onTertiaryContainer = Color(0xFFE5E7AE),
    background = Color(0xFF18120D),
    onBackground = Color(0xFFEDE0D7),
    surface = Color(0xFF18120D),
    onSurface = Color(0xFFEDE0D7),
    surfaceVariant = Color(0xFF50443B),
    onSurfaceVariant = Color(0xFFD5C3B6),
    outline = Color(0xFF9E8D80),
    outlineVariant = Color(0xFF50443B),
    inverseSurface = Color(0xFFEDE0D7),
    inverseOnSurface = Color(0xFF362F29),
    surfaceContainerLow = Color(0xFF211A15),
    surfaceContainer = Color(0xFF261E19),
    surfaceContainerHigh = Color(0xFF302823),
    surfaceContainerHighest = Color(0xFF3C332D),
)
