#!/usr/bin/env python3
"""Add remaining hardcoded Chinese string resources for Phase 10+ i18n."""
import os

BASE = "/Users/driezy/Downloads/MedLogAndroid/app/src/main/res"
LOCALE_MAP = {"zh": "values", "en": "values-en", "ja": "values-ja", "ko": "values-ko"}

STRINGS = {
    "zh": [
        # ── 通用操作（多处复用） ─────────────────────────────────────
        ("common_action_delete",    "删除"),
        ("common_action_cancel",    "取消"),
        ("common_action_edit",      "编辑"),
        ("common_action_save",      "保存"),
        ("common_action_add",       "添加"),
        ("common_irrev_warning",    "此操作无法撤销。"),
        ("common_notes_hint",       "备注（可选）"),
        ("common_no_plan_today",    "今日暂无用药计划"),
        ("common_filter_all",       "全部"),
        # ── TimePeriod 枚举标签 ──────────────────────────────────────
        ("time_period_exact",           "精确时间"),
        ("time_period_morning",         "早晨"),
        ("time_period_after_breakfast", "早餐后"),
        ("time_period_before_lunch",    "午餐前"),
        ("time_period_after_lunch",     "午餐后"),
        ("time_period_before_dinner",   "晚餐前"),
        ("time_period_after_dinner",    "晚餐后"),
        ("time_period_evening",         "晚间"),
        ("time_period_bedtime",         "睡前"),
        ("time_period_before_breakfast","早餐前"),
        ("time_period_afternoon",       "下午"),
        # ── HealthType 枚举标签 ──────────────────────────────────────
        ("health_type_label_blood_pressure", "血压"),
        ("health_type_label_blood_glucose",  "血糖"),
        ("health_type_label_weight",         "体重"),
        ("health_type_label_heart_rate",     "心率"),
        ("health_type_label_temperature",    "体温"),
        ("health_type_label_spo2",           "血氧"),
        # ── MedicationCard ───────────────────────────────────────────
        ("med_card_high_priority_cd", "高优先级"),
        ("med_card_tcm_label",        "中成药"),
        ("med_card_taken_at",         "✓ 已于 %s 服用"),
        ("med_card_skipped_today",    "今日已跳过"),
        ("med_card_low_stock",        "库存不足（剩余 %1$s %2$s）"),
        ("med_card_btn_take",         "服用"),
        # ── ProgressHeader ───────────────────────────────────────────
        ("progress_header_title",     "今日进度"),
        ("progress_header_all_done",  "全部完成！🎉"),
        ("progress_header_remaining", "还剩 %d 种药品待服用"),
        # ── SymptomDiaryScreen ───────────────────────────────────────
        ("symptom_screen_title",        "症状日记"),
        ("symptom_screen_fab_cd",       "记录症状"),
        ("symptom_empty_title",         "还没有日记记录"),
        ("symptom_empty_body",          "点击右下角 + 开始记录今天的状态"),
        ("symptom_delete_title",        "删除记录"),
        ("symptom_delete_body",         "确定要删除这条症状日记吗？此操作无法撤销。"),
        ("symptom_card_symptoms_label", "症状"),
        ("symptom_card_sideeff_label",  "副作用"),
        ("symptom_dialog_add_title",    "记录今天的状态"),
        ("symptom_dialog_edit_title",   "编辑记录"),
        ("symptom_rating_label",        "整体感受"),
        ("symptom_rating_1",            "很差"),
        ("symptom_rating_2",            "较差"),
        ("symptom_rating_3",            "一般"),
        ("symptom_rating_4",            "较好"),
        ("symptom_rating_5",            "很好"),
        ("symptom_section_symptoms",    "症状（可多选）"),
        ("symptom_custom_input_label",  "自定义症状"),
        ("symptom_section_side_effects","副作用（可多选）"),
        ("symptom_custom_se_label",     "自定义副作用"),
        ("symptom_save_btn",            "保存记录"),
        # ── HealthScreen ─────────────────────────────────────────────
        ("health_screen_title",          "健康体征"),
        ("health_screen_fab_cd",         "记录体征"),
        ("health_empty_hint",            "暂无记录，点击 + 开始记录"),
        ("health_delete_title",          "删除记录"),
        ("health_delete_body",           "确定要删除这条体征记录吗？此操作无法撤销。"),
        ("health_7day_avg",              "7日均 %s"),
        ("health_more_ops_cd",           "更多操作"),
        ("health_sheet_add_title",       "记录体征"),
        ("health_sheet_edit_title",      "编辑记录"),
        ("health_type_selector_label",   "体征类型"),
        ("health_bp_systolic",           "收缩压"),
        ("health_bp_diastolic",          "舒张压"),
        ("health_normal_range",          "正常范围：%1$s–%2$s %3$s"),
        # ── MedicationDetailScreen 剩余 ──────────────────────────────
        ("detail_category_label",        "分类"),
        ("detail_batch_label",           "批量"),
        # ── 导航/日期 ─────────────────────────────────────────────────
        ("nav_drawer_title",             "用药日志"),
        ("date_format_day_label",        "M月d日 EEEE"),
        ("date_format_log_item",         "M月d日 HH:mm"),
        # ── Widget 通用 ───────────────────────────────────────────────
        ("widget_all_done",              "全部完成"),
        ("widget_all_done_msg",          "🎉 今日用药全部完成！"),
        ("widget_taken_label",           "已服"),
        ("widget_pending_label",         "待服"),
        ("widget_no_plan",               "无计划"),
        ("widget_no_plan_today",         "今日暂无用药计划"),
        ("widget_add_prompt",            "点击进入添加 →"),
        ("widget_goal_done",             "全部 ✓"),
        ("widget_remaining_fmt",         "…还有 %d 种"),
        ("widget_app_label",             "用药日志"),
        ("widget_today_done_label",      "今日完成"),
        # ── StreakWidget ──────────────────────────────────────────────
        ("widget_streak_title",          "连续打卡"),
        ("widget_streak_days_fmt",       "🔥 %d 天"),
        ("widget_streak_zero",           "0 天"),
        ("widget_streak_days_unit",      "天"),
        ("widget_weekday_sun",           "日"),
        ("widget_weekday_mon",           "一"),
        ("widget_weekday_tue",           "二"),
        ("widget_weekday_wed",           "三"),
        ("widget_weekday_thu",           "四"),
        ("widget_weekday_fri",           "五"),
        ("widget_weekday_sat",           "六"),
        # ── NextDoseWidget ────────────────────────────────────────────
        ("widget_next_dose_title",         "下次服药"),
        ("widget_next_dose_now",           "现在服药"),
        ("widget_next_dose_min_fmt",       "还有 %d 分钟"),
        ("widget_next_dose_1h_min_fmt",    "还有 1 小时 %d 分钟"),
        ("widget_next_dose_h_fmt",         "还有约 %d 小时"),
        ("widget_next_dose_no_pending",    "暂无待服药品"),
        ("widget_next_dose_more_fmt",      "+%d 种"),
        ("widget_next_dose_remaining_fmt", "…还有 %d 种"),
        # ── OemWidgetHelper (长文本保留英文备注用途，仅加中文版本)────
        ("oem_miui_pin_guide",
         "MIUI / HyperOS 设备需手动开启「桌面快捷方式」权限后，固定小组件对话框才会弹出。\n路径：设置 → 应用设置 → 授权管理 → MedLog → 桌面快捷方式 → 允许"),
        ("oem_coloros_pin_guide",
         "ColorOS / OxygenOS 设备需手动开启「桌面快捷方式」权限。\n路径：设置 → 隐私 → 权限管理 → MedLog → 桌面快捷方式 → 允许"),
        ("oem_originos_pin_guide",
         "OriginOS / Funtouch OS 设备需手动开启「桌面快捷方式」权限。\n路径：设置 → 隐私权限 → 权限 → 桌面快捷方式 → MedLog → 允许"),
        ("oem_manual_add_guide",
         "请长按桌面空白区域 → 小组件 → MedLog，手动拖拽添加到桌面。"),
    ],
    "en": [
        ("common_action_delete",    "Delete"),
        ("common_action_cancel",    "Cancel"),
        ("common_action_edit",      "Edit"),
        ("common_action_save",      "Save"),
        ("common_action_add",       "Add"),
        ("common_irrev_warning",    "This action cannot be undone."),
        ("common_notes_hint",       "Notes (optional)"),
        ("common_no_plan_today",    "No medications scheduled for today"),
        ("common_filter_all",       "All"),
        ("time_period_exact",           "Exact time"),
        ("time_period_morning",         "Morning"),
        ("time_period_after_breakfast", "After breakfast"),
        ("time_period_before_lunch",    "Before lunch"),
        ("time_period_after_lunch",     "After lunch"),
        ("time_period_before_dinner",   "Before dinner"),
        ("time_period_after_dinner",    "After dinner"),
        ("time_period_evening",         "Evening"),
        ("time_period_bedtime",         "Bedtime"),
        ("time_period_before_breakfast","Before breakfast"),
        ("time_period_afternoon",       "Afternoon"),
        ("health_type_label_blood_pressure", "Blood pressure"),
        ("health_type_label_blood_glucose",  "Blood glucose"),
        ("health_type_label_weight",         "Weight"),
        ("health_type_label_heart_rate",     "Heart rate"),
        ("health_type_label_temperature",    "Temperature"),
        ("health_type_label_spo2",           "SpO2"),
        ("med_card_high_priority_cd", "High priority"),
        ("med_card_tcm_label",        "TCM"),
        ("med_card_taken_at",         "✓ Taken at %s"),
        ("med_card_skipped_today",    "Skipped today"),
        ("med_card_low_stock",        "Low stock (%1$s %2$s remaining)"),
        ("med_card_btn_take",         "Take"),
        ("progress_header_title",     "Today\'s progress"),
        ("progress_header_all_done",  "All done! 🎉"),
        ("progress_header_remaining", "%d medication(s) remaining"),
        ("symptom_screen_title",        "Symptom Diary"),
        ("symptom_screen_fab_cd",       "Log symptoms"),
        ("symptom_empty_title",         "No diary entries yet"),
        ("symptom_empty_body",          "Tap + below to start recording today\'s status"),
        ("symptom_delete_title",        "Delete Entry"),
        ("symptom_delete_body",         "Are you sure you want to delete this diary entry? This action cannot be undone."),
        ("symptom_card_symptoms_label", "Symptoms"),
        ("symptom_card_sideeff_label",  "Side effects"),
        ("symptom_dialog_add_title",    "Record today\'s status"),
        ("symptom_dialog_edit_title",   "Edit entry"),
        ("symptom_rating_label",        "Overall feeling"),
        ("symptom_rating_1",            "Very bad"),
        ("symptom_rating_2",            "Bad"),
        ("symptom_rating_3",            "Okay"),
        ("symptom_rating_4",            "Good"),
        ("symptom_rating_5",            "Very good"),
        ("symptom_section_symptoms",    "Symptoms (multi-select)"),
        ("symptom_custom_input_label",  "Custom symptom"),
        ("symptom_section_side_effects","Side effects (multi-select)"),
        ("symptom_custom_se_label",     "Custom side effect"),
        ("symptom_save_btn",            "Save entry"),
        ("health_screen_title",          "Health Vitals"),
        ("health_screen_fab_cd",         "Record vital"),
        ("health_empty_hint",            "No records yet. Tap + to start"),
        ("health_delete_title",          "Delete Record"),
        ("health_delete_body",           "Are you sure you want to delete this vital record? This action cannot be undone."),
        ("health_7day_avg",              "7d avg %s"),
        ("health_more_ops_cd",           "More options"),
        ("health_sheet_add_title",       "Record vital"),
        ("health_sheet_edit_title",      "Edit record"),
        ("health_type_selector_label",   "Vital type"),
        ("health_bp_systolic",           "Systolic"),
        ("health_bp_diastolic",          "Diastolic"),
        ("health_normal_range",          "Normal range: %1$s–%2$s %3$s"),
        ("detail_category_label",        "Category"),
        ("detail_batch_label",           "Batch"),
        ("nav_drawer_title",             "Med Log"),
        ("date_format_day_label",        "MMMM d, EEEE"),
        ("date_format_log_item",         "MMM d HH:mm"),
        ("widget_all_done",              "All done"),
        ("widget_all_done_msg",          "🎉 All meds taken today!"),
        ("widget_taken_label",           "Taken"),
        ("widget_pending_label",         "Pending"),
        ("widget_no_plan",               "No plan"),
        ("widget_no_plan_today",         "No medications today"),
        ("widget_add_prompt",            "Tap to add →"),
        ("widget_goal_done",             "All ✓"),
        ("widget_remaining_fmt",         "…%d more"),
        ("widget_app_label",             "Med Log"),
        ("widget_today_done_label",      "Done today"),
        ("widget_streak_title",          "Streak"),
        ("widget_streak_days_fmt",       "🔥 %d days"),
        ("widget_streak_zero",           "0 days"),
        ("widget_streak_days_unit",      "d"),
        ("widget_weekday_sun",           "Sun"),
        ("widget_weekday_mon",           "Mon"),
        ("widget_weekday_tue",           "Tue"),
        ("widget_weekday_wed",           "Wed"),
        ("widget_weekday_thu",           "Thu"),
        ("widget_weekday_fri",           "Fri"),
        ("widget_weekday_sat",           "Sat"),
        ("widget_next_dose_title",         "Next dose"),
        ("widget_next_dose_now",           "Take now"),
        ("widget_next_dose_min_fmt",       "In %d min"),
        ("widget_next_dose_1h_min_fmt",    "In 1h %d min"),
        ("widget_next_dose_h_fmt",         "In ~%d h"),
        ("widget_next_dose_no_pending",    "No pending meds"),
        ("widget_next_dose_more_fmt",      "+%d more"),
        ("widget_next_dose_remaining_fmt", "…%d more"),
        ("oem_miui_pin_guide",
         "On MIUI / HyperOS, enable \'Desktop shortcut\' permission to allow widget pinning.\nPath: Settings → App settings → Permissions → MedLog → Desktop shortcut → Allow"),
        ("oem_coloros_pin_guide",
         "On ColorOS / OxygenOS, enable \'Desktop shortcut\' permission.\nPath: Settings → Privacy → Permission management → MedLog → Desktop shortcut → Allow"),
        ("oem_originos_pin_guide",
         "On OriginOS / Funtouch OS, enable \'Desktop shortcut\' permission.\nPath: Settings → Privacy → Permissions → Desktop shortcut → MedLog → Allow"),
        ("oem_manual_add_guide",
         "Long-press a blank area on your home screen → Widgets → MedLog, then drag to add."),
    ],
    "ja": [
        ("common_action_delete",    "削除"),
        ("common_action_cancel",    "キャンセル"),
        ("common_action_edit",      "編集"),
        ("common_action_save",      "保存"),
        ("common_action_add",       "追加"),
        ("common_irrev_warning",    "この操作は取り消せません。"),
        ("common_notes_hint",       "メモ（任意）"),
        ("common_no_plan_today",    "本日の服薬予定はありません"),
        ("common_filter_all",       "すべて"),
        ("time_period_exact",           "指定時刻"),
        ("time_period_morning",         "朝"),
        ("time_period_after_breakfast", "朝食後"),
        ("time_period_before_lunch",    "昼食前"),
        ("time_period_after_lunch",     "昼食後"),
        ("time_period_before_dinner",   "夕食前"),
        ("time_period_after_dinner",    "夕食後"),
        ("time_period_evening",         "夕方"),
        ("time_period_bedtime",         "就寝前"),
        ("time_period_before_breakfast","朝食前"),
        ("time_period_afternoon",       "午後"),
        ("health_type_label_blood_pressure", "血圧"),
        ("health_type_label_blood_glucose",  "血糖"),
        ("health_type_label_weight",         "体重"),
        ("health_type_label_heart_rate",     "心拍数"),
        ("health_type_label_temperature",    "体温"),
        ("health_type_label_spo2",           "SpO2"),
        ("med_card_high_priority_cd", "高優先度"),
        ("med_card_tcm_label",        "漢方薬"),
        ("med_card_taken_at",         "✓ %s に服用"),
        ("med_card_skipped_today",    "本日スキップ"),
        ("med_card_low_stock",        "在庫不足（残り %1$s %2$s）"),
        ("med_card_btn_take",         "服薬"),
        ("progress_header_title",     "本日の進捗"),
        ("progress_header_all_done",  "すべて完了！🎉"),
        ("progress_header_remaining", "残り %d 種類"),
        ("symptom_screen_title",        "症状日記"),
        ("symptom_screen_fab_cd",       "症状を記録"),
        ("symptom_empty_title",         "まだ日記がありません"),
        ("symptom_empty_body",          "右下の + タップで今日の状態を記録しましょう"),
        ("symptom_delete_title",        "記録を削除"),
        ("symptom_delete_body",         "この症状日記を削除しますか？この操作は取り消せません。"),
        ("symptom_card_symptoms_label", "症状"),
        ("symptom_card_sideeff_label",  "副作用"),
        ("symptom_dialog_add_title",    "今日の状態を記録"),
        ("symptom_dialog_edit_title",   "記録を編集"),
        ("symptom_rating_label",        "全体的な感覚"),
        ("symptom_rating_1",            "とても悪い"),
        ("symptom_rating_2",            "悪い"),
        ("symptom_rating_3",            "普通"),
        ("symptom_rating_4",            "良い"),
        ("symptom_rating_5",            "とても良い"),
        ("symptom_section_symptoms",    "症状（複数選択可）"),
        ("symptom_custom_input_label",  "カスタム症状"),
        ("symptom_section_side_effects","副作用（複数選択可）"),
        ("symptom_custom_se_label",     "カスタム副作用"),
        ("symptom_save_btn",            "記録を保存"),
        ("health_screen_title",          "健康バイタル"),
        ("health_screen_fab_cd",         "バイタルを記録"),
        ("health_empty_hint",            "記録がありません。+ をタップして開始"),
        ("health_delete_title",          "記録を削除"),
        ("health_delete_body",           "このバイタル記録を削除しますか？この操作は取り消せません。"),
        ("health_7day_avg",              "7日平均 %s"),
        ("health_more_ops_cd",           "その他の操作"),
        ("health_sheet_add_title",       "バイタルを記録"),
        ("health_sheet_edit_title",      "記録を編集"),
        ("health_type_selector_label",   "バイタルの種類"),
        ("health_bp_systolic",           "最高血圧"),
        ("health_bp_diastolic",          "最低血圧"),
        ("health_normal_range",          "正常範囲：%1$s–%2$s %3$s"),
        ("detail_category_label",        "カテゴリ"),
        ("detail_batch_label",           "バッチ"),
        ("nav_drawer_title",             "服薬ログ"),
        ("date_format_day_label",        "M月d日(EEEE)"),
        ("date_format_log_item",         "M月d日 HH:mm"),
        ("widget_all_done",              "すべて完了"),
        ("widget_all_done_msg",          "🎉 本日の服薬がすべて完了！"),
        ("widget_taken_label",           "服薬済"),
        ("widget_pending_label",         "未服薬"),
        ("widget_no_plan",               "予定なし"),
        ("widget_no_plan_today",         "本日の服薬予定はありません"),
        ("widget_add_prompt",            "タップして追加 →"),
        ("widget_goal_done",             "すべて ✓"),
        ("widget_remaining_fmt",         "…あと %d 種"),
        ("widget_app_label",             "服薬ログ"),
        ("widget_today_done_label",      "本日完了"),
        ("widget_streak_title",          "連続記録"),
        ("widget_streak_days_fmt",       "🔥 %d 日"),
        ("widget_streak_zero",           "0 日"),
        ("widget_streak_days_unit",      "日"),
        ("widget_weekday_sun",           "日"),
        ("widget_weekday_mon",           "月"),
        ("widget_weekday_tue",           "火"),
        ("widget_weekday_wed",           "水"),
        ("widget_weekday_thu",           "木"),
        ("widget_weekday_fri",           "金"),
        ("widget_weekday_sat",           "土"),
        ("widget_next_dose_title",         "次の服薬"),
        ("widget_next_dose_now",           "今すぐ服薬"),
        ("widget_next_dose_min_fmt",       "あと %d 分"),
        ("widget_next_dose_1h_min_fmt",    "あと 1 時間 %d 分"),
        ("widget_next_dose_h_fmt",         "あと約 %d 時間"),
        ("widget_next_dose_no_pending",    "服薬予定なし"),
        ("widget_next_dose_more_fmt",      "+%d 種"),
        ("widget_next_dose_remaining_fmt", "…あと %d 種"),
        ("oem_miui_pin_guide",
         "MIUI / HyperOS では「デスクトップショートカット」権限を有効にする必要があります。\nパス：設定 → アプリ設定 → 認証管理 → MedLog → デスクトップショートカット → 許可"),
        ("oem_coloros_pin_guide",
         "ColorOS / OxygenOS では「デスクトップショートカット」権限が必要です。\nパス：設定 → プライバシー → 権限管理 → MedLog → デスクトップショートカット → 許可"),
        ("oem_originos_pin_guide",
         "OriginOS / Funtouch OS では「デスクトップショートカット」権限が必要です。\nパス：設定 → プライバシー → 権限 → デスクトップショートカット → MedLog → 許可"),
        ("oem_manual_add_guide",
         "ホーム画面の空白領域を長押し → ウィジェット → MedLog を選んでドラッグ追加してください。"),
    ],
    "ko": [
        ("common_action_delete",    "삭제"),
        ("common_action_cancel",    "취소"),
        ("common_action_edit",      "편집"),
        ("common_action_save",      "저장"),
        ("common_action_add",       "추가"),
        ("common_irrev_warning",    "이 작업은 되돌릴 수 없습니다."),
        ("common_notes_hint",       "메모 (선택 사항)"),
        ("common_no_plan_today",    "오늘 예정된 복약이 없습니다"),
        ("common_filter_all",       "전체"),
        ("time_period_exact",           "정확한 시간"),
        ("time_period_morning",         "아침"),
        ("time_period_after_breakfast", "아침 식사 후"),
        ("time_period_before_lunch",    "점심 전"),
        ("time_period_after_lunch",     "점심 후"),
        ("time_period_before_dinner",   "저녁 전"),
        ("time_period_after_dinner",    "저녁 후"),
        ("time_period_evening",         "저녁"),
        ("time_period_bedtime",         "취침 전"),
        ("time_period_before_breakfast","아침 식사 전"),
        ("time_period_afternoon",       "오후"),
        ("health_type_label_blood_pressure", "혈압"),
        ("health_type_label_blood_glucose",  "혈당"),
        ("health_type_label_weight",         "체중"),
        ("health_type_label_heart_rate",     "심박수"),
        ("health_type_label_temperature",    "체온"),
        ("health_type_label_spo2",           "혈중 산소"),
        ("med_card_high_priority_cd", "높은 우선순위"),
        ("med_card_tcm_label",        "한약"),
        ("med_card_taken_at",         "✓ %s에 복용"),
        ("med_card_skipped_today",    "오늘 건너뜀"),
        ("med_card_low_stock",        "재고 부족 (%1$s %2$s 남음)"),
        ("med_card_btn_take",         "복용"),
        ("progress_header_title",     "오늘의 진행상황"),
        ("progress_header_all_done",  "모두 완료! 🎉"),
        ("progress_header_remaining", "남은 약 %d 종"),
        ("symptom_screen_title",        "증상 일기"),
        ("symptom_screen_fab_cd",       "증상 기록"),
        ("symptom_empty_title",         "아직 일기 기록이 없습니다"),
        ("symptom_empty_body",          "오른쪽 하단 + 를 탭해 오늘의 상태를 기록하세요"),
        ("symptom_delete_title",        "기록 삭제"),
        ("symptom_delete_body",         "이 증상 일기를 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다."),
        ("symptom_card_symptoms_label", "증상"),
        ("symptom_card_sideeff_label",  "부작용"),
        ("symptom_dialog_add_title",    "오늘의 상태 기록"),
        ("symptom_dialog_edit_title",   "기록 편집"),
        ("symptom_rating_label",        "전반적인 상태"),
        ("symptom_rating_1",            "매우 나쁨"),
        ("symptom_rating_2",            "나쁨"),
        ("symptom_rating_3",            "보통"),
        ("symptom_rating_4",            "좋음"),
        ("symptom_rating_5",            "매우 좋음"),
        ("symptom_section_symptoms",    "증상 (다중 선택)"),
        ("symptom_custom_input_label",  "사용자 정의 증상"),
        ("symptom_section_side_effects","부작용 (다중 선택)"),
        ("symptom_custom_se_label",     "사용자 정의 부작용"),
        ("symptom_save_btn",            "기록 저장"),
        ("health_screen_title",          "건강 바이탈"),
        ("health_screen_fab_cd",         "바이탈 기록"),
        ("health_empty_hint",            "기록이 없습니다. + 를 탭해 시작하세요"),
        ("health_delete_title",          "기록 삭제"),
        ("health_delete_body",           "이 바이탈 기록을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다."),
        ("health_7day_avg",              "7일 평균 %s"),
        ("health_more_ops_cd",           "더 많은 옵션"),
        ("health_sheet_add_title",       "바이탈 기록"),
        ("health_sheet_edit_title",      "기록 편집"),
        ("health_type_selector_label",   "바이탈 유형"),
        ("health_bp_systolic",           "수축기"),
        ("health_bp_diastolic",          "이완기"),
        ("health_normal_range",          "정상 범위: %1$s–%2$s %3$s"),
        ("detail_category_label",        "카테고리"),
        ("detail_batch_label",           "배치"),
        ("nav_drawer_title",             "복약 로그"),
        ("date_format_day_label",        "M월 d일 EEEE"),
        ("date_format_log_item",         "M월 d일 HH:mm"),
        ("widget_all_done",              "모두 완료"),
        ("widget_all_done_msg",          "🎉 오늘 모든 약을 복용했습니다!"),
        ("widget_taken_label",           "복용"),
        ("widget_pending_label",         "대기"),
        ("widget_no_plan",               "계획 없음"),
        ("widget_no_plan_today",         "오늘 복약 예정 없음"),
        ("widget_add_prompt",            "탭하여 추가 →"),
        ("widget_goal_done",             "전부 ✓"),
        ("widget_remaining_fmt",         "…%d 종 더"),
        ("widget_app_label",             "복약 로그"),
        ("widget_today_done_label",      "오늘 완료"),
        ("widget_streak_title",          "연속 기록"),
        ("widget_streak_days_fmt",       "🔥 %d 일"),
        ("widget_streak_zero",           "0 일"),
        ("widget_streak_days_unit",      "일"),
        ("widget_weekday_sun",           "일"),
        ("widget_weekday_mon",           "월"),
        ("widget_weekday_tue",           "화"),
        ("widget_weekday_wed",           "수"),
        ("widget_weekday_thu",           "목"),
        ("widget_weekday_fri",           "금"),
        ("widget_weekday_sat",           "토"),
        ("widget_next_dose_title",         "다음 복약"),
        ("widget_next_dose_now",           "지금 복용"),
        ("widget_next_dose_min_fmt",       "%d분 후"),
        ("widget_next_dose_1h_min_fmt",    "1시간 %d분 후"),
        ("widget_next_dose_h_fmt",         "약 %d시간 후"),
        ("widget_next_dose_no_pending",    "대기 중인 약 없음"),
        ("widget_next_dose_more_fmt",      "+%d 종"),
        ("widget_next_dose_remaining_fmt", "…%d 종 더"),
        ("oem_miui_pin_guide",
         "MIUI / HyperOS에서는 위젯 고정 대화상자를 활성화하려면 \'바탕화면 바로가기\' 권한을 수동으로 활성화해야 합니다.\n경로: 설정 → 앱 설정 → 권한 관리 → MedLog → 바탕화면 바로가기 → 허용"),
        ("oem_coloros_pin_guide",
         "ColorOS / OxygenOS에서는 \'바탕화면 바로가기\' 권한이 필요합니다.\n경로: 설정 → 개인 정보 → 권한 관리 → MedLog → 바탕화면 바로가기 → 허용"),
        ("oem_originos_pin_guide",
         "OriginOS / Funtouch OS에서는 \'바탕화면 바로가기\' 권한이 필요합니다.\n경로: 설정 → 개인 정보 → 권한 → 바탕화면 바로가기 → MedLog → 허용"),
        ("oem_manual_add_guide",
         "홈 화면 빈 곳을 길게 눌러 → 위젯 → MedLog를 선택하고 끌어 추가하세요."),
    ],
}


def add_strings(lang: str, entries: list) -> int:
    folder = os.path.join(BASE, LOCALE_MAP[lang])
    path = os.path.join(folder, "strings.xml")
    with open(path, encoding="utf-8") as f:
        content = f.read()
    count = 0
    for key, val in entries:
        if f'name="{key}"' in content:
            continue
        val_escaped = val.replace("'", "\\'").replace("&", "&amp;")
        entry = f'    <string name="{key}">{val_escaped}</string>'
        content = content.replace("</resources>", f"{entry}\n</resources>")
        count += 1
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return count


for lang, entries in STRINGS.items():
    n = add_strings(lang, entries)
    print(f"[{lang}] Added {n} keys")

print("Done!")
