package com.example.medlog.ui.theme

import androidx.compose.ui.graphics.Color

// ── Brand colors (医疗蓝+绿色调，Material Theme Builder 生成) ─────────────────

val primaryLight                    = Color(0xFF1B6391)
val onPrimaryLight                  = Color(0xFFFFFFFF)
val primaryContainerLight           = Color(0xFFCBE6FF)
val onPrimaryContainerLight         = Color(0xFF001E30)
val secondaryLight                  = Color(0xFF4E616E)
val onSecondaryLight                = Color(0xFFFFFFFF)
val secondaryContainerLight         = Color(0xFFD1E5F5)
val onSecondaryContainerLight       = Color(0xFF0A1E29)
val tertiaryLight                   = Color(0xFF3B6939)
val onTertiaryLight                 = Color(0xFFFFFFFF)
val tertiaryContainerLight          = Color(0xFFBBF0B3)
val onTertiaryContainerLight        = Color(0xFF002203)
val errorLight                      = Color(0xFFBA1A1A)
val onErrorLight                    = Color(0xFFFFFFFF)
val errorContainerLight             = Color(0xFFFFDAD6)
val onErrorContainerLight           = Color(0xFF410002)
val backgroundLight                 = Color(0xFFF7FAFE)
val onBackgroundLight               = Color(0xFF181C1F)
val surfaceLight                    = Color(0xFFF7FAFE)
val onSurfaceLight                  = Color(0xFF181C1F)
val surfaceVariantLight             = Color(0xFFDCE4EA)
val onSurfaceVariantLight           = Color(0xFF40484D)
val outlineLight                    = Color(0xFF70787D)
val outlineVariantLight             = Color(0xFFC0C8CE)
val inverseSurfaceLight             = Color(0xFF2D3135)
val inverseOnSurfaceLight           = Color(0xFFEEF2F6)
val inversePrimaryLight             = Color(0xFF93CDF5)

val primaryDark                     = Color(0xFF93CDF5)
val onPrimaryDark                   = Color(0xFF00344F)
val primaryContainerDark            = Color(0xFF004B70)
val onPrimaryContainerDark          = Color(0xFFCBE6FF)
val secondaryDark                   = Color(0xFFB5C9D7)
val onSecondaryDark                 = Color(0xFF1F333E)
val secondaryContainerDark          = Color(0xFF364A56)
val onSecondaryContainerDark        = Color(0xFFD1E5F5)
val tertiaryDark                    = Color(0xFFA0D499)
val onTertiaryDark                  = Color(0xFF07390C)
val tertiaryContainerDark           = Color(0xFF235024)
val onTertiaryContainerDark         = Color(0xFFBBF0B3)
val errorDark                       = Color(0xFFFFB4AB)
val onErrorDark                     = Color(0xFF690005)
val errorContainerDark              = Color(0xFF93000A)
val onErrorContainerDark            = Color(0xFFFFDAD6)
val backgroundDark                  = Color(0xFF0F1417)
val onBackgroundDark                = Color(0xFFDEE3E7)
val surfaceDark                     = Color(0xFF0F1417)
val onSurfaceDark                   = Color(0xFFDEE3E7)
val surfaceVariantDark              = Color(0xFF40484D)
val onSurfaceVariantDark            = Color(0xFFC0C8CE)
val outlineDark                     = Color(0xFF8A9297)
val outlineVariantDark              = Color(0xFF40484D)
val inverseSurfaceDark              = Color(0xFFDEE3E7)
val inverseOnSurfaceDark            = Color(0xFF2D3135)
val inversePrimaryDark              = Color(0xFF1B6391)
