#!/usr/bin/env zsh
# setup-signing.sh — 在新 Mac 上一键恢复 Release 签名配置
#
# 前提（换机器后 iCloud 同步完成即已满足）：
#   1. iCloud Drive 已同步 ~/Library/Mobile Documents/com~apple~CloudDocs/Dev/Keystores/medlog-release.jks
#   2. iCloud Keychain 已同步密码条目 (服务: MedLogAndroid-Keystore)
#
# 用法：
#   chmod +x scripts/setup-signing.sh
#   ./scripts/setup-signing.sh

set -e

ICLOUD_JKS="$HOME/Library/Mobile Documents/com~apple~CloudDocs/Dev/Keystores/medlog-release.jks"
KEYCHAIN_SERVICE="MedLogAndroid-Keystore"
KEYCHAIN_ACCOUNT="release"
LOCAL_PROPS="$(dirname "$0")/../local.properties"

echo "🔑 MedLog Release 签名配置初始化"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# 1. 检查 keystore 文件
if [ ! -f "$ICLOUD_JKS" ]; then
  echo "❌ 找不到 keystore 文件：$ICLOUD_JKS"
  echo "   请确认 iCloud Drive 已同步完成，或手动将 .jks 文件放到上述路径。"
  exit 1
fi
echo "✅ Keystore：$ICLOUD_JKS"

# 2. 从 macOS Keychain 读取密码
PASS=$(security find-generic-password \
  -a "$KEYCHAIN_ACCOUNT" \
  -s "$KEYCHAIN_SERVICE" \
  -w 2>/dev/null || true)

if [ -z "$PASS" ]; then
  echo "⚠️  Keychain 中未找到密码 (服务: $KEYCHAIN_SERVICE)"
  echo -n "   请手动输入 Keystore 密码并按 Enter："; read -rs PASS; echo
  # 顺便存入本机 Keychain
  security add-generic-password -a "$KEYCHAIN_ACCOUNT" -s "$KEYCHAIN_SERVICE" -w "$PASS" -T "" 2>/dev/null || true
  echo "   ✅ 密码已保存到本机 Keychain"
else
  echo "✅ 已从 Keychain 读取密码"
fi

# 3. 写入 local.properties（保留已有的 sdk.dir 等行）
touch "$LOCAL_PROPS"
grep -v "^KEYSTORE\|^KEY_" "$LOCAL_PROPS" > /tmp/_lp_tmp || true
mv /tmp/_lp_tmp "$LOCAL_PROPS"

cat >> "$LOCAL_PROPS" << PROPS

# Release signing (iCloud Drive JKS + Keychain password) — auto-generated by setup-signing.sh
KEYSTORE_PATH=$ICLOUD_JKS
KEYSTORE_PASSWORD=$PASS
KEY_ALIAS=$KEYCHAIN_ACCOUNT
KEY_PASSWORD=$PASS
PROPS

echo "✅ local.properties 已更新"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎉 完成！现在可以运行：./gradlew assembleRelease"
echo ""
echo "💡 提示：如需配置 GitHub Actions 签名，请运行以下命令获取 Secrets 值："
echo "   base64 -i \"$ICLOUD_JKS\" | pbcopy   # KEYSTORE_BASE64 已复制到剪贴板"
echo "   security find-generic-password -a release -s MedLogAndroid-Keystore -w   # KEYSTORE_PASSWORD"
